apiVersion: v1
kind: Service
metadata:
  name: {{ include "tcs.fullname" . }}
  labels:
    {{- include "tcs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if ne .Values.service.type "ClusterIP" }}
    - port: {{ .Values.siderolink.listenPort }}
      targetPort: siderolink
      protocol: TCP
      name: siderolink
    {{- end }}
  selector:
    {{- include "tcs.selectorLabels" . | nindent 4 }}
