//! Greenfield config factory: generate Talos secrets + machine configs.

use std::path::PathBuf;
use std::process::Command;

use chrono::Utc;
use sqlx::SqlitePool;
use uuid::Uuid;

use crate::db::repos::provision::{self, ProvisionArtifact};
use crate::utils::secrets;
use crate::AppError;

pub struct ProvisionController {
    pool: SqlitePool,
    jwt_secret: String,
}

impl ProvisionController {
    pub fn new(pool: SqlitePool, jwt_secret: String) -> Self {
        Self { pool, jwt_secret }
    }

    /// Generate configs via `talosctl gen config` when available; otherwise emit a template stub.
    pub async fn generate_config(
        &self,
        name: &str,
        endpoint: &str,
        talos_version: &str,
        kubernetes_version: &str,
        cluster_id: Option<Uuid>,
    ) -> Result<ProvisionArtifact, AppError> {
        if name.trim().is_empty() || endpoint.trim().is_empty() {
            return Err(AppError::InvalidInput(
                "name and endpoint are required".into(),
            ));
        }

        let tmp = tempfile::tempdir().map_err(|e| {
            AppError::Io(std::io::Error::new(
                e.kind(),
                format!("temp dir for gen config: {}", e),
            ))
        })?;
        let out = tmp.path();

        let (cp, worker, secrets_plain) =
            match gen_with_talosctl(name, endpoint, out) {
                Ok(v) => v,
                Err(e) => {
                    tracing::warn!(error = %e, "talosctl gen config failed; using template stub");
                    gen_template_stub(name, endpoint, talos_version, kubernetes_version)
                }
            };

        let secrets_enc = secrets::encrypt(&self.jwt_secret, &secrets_plain)?;
        let art = ProvisionArtifact {
            id: Uuid::new_v4(),
            cluster_id,
            name: name.to_string(),
            talos_version: talos_version.to_string(),
            kubernetes_version: kubernetes_version.to_string(),
            secrets_enc: Some(secrets_enc),
            controlplane_config: Some(cp),
            worker_config: Some(worker),
            created_at: Utc::now(),
        };
        provision::create(&self.pool, &art).await?;
        Ok(art)
    }

    pub async fn get(&self, id: Uuid) -> Result<ProvisionArtifact, AppError> {
        provision::get(&self.pool, id)
            .await?
            .ok_or_else(|| AppError::NotFound(format!("Provision artifact {} not found", id)))
    }

    pub async fn list(&self) -> Result<Vec<ProvisionArtifact>, AppError> {
        provision::list(&self.pool).await
    }
}

fn gen_with_talosctl(
    name: &str,
    endpoint: &str,
    out: &std::path::Path,
) -> Result<(String, String, String), String> {
    let status = Command::new("talosctl")
        .args([
            "gen",
            "config",
            name,
            endpoint,
            "--output-dir",
            out.to_str().unwrap_or("/tmp"),
            "--force",
        ])
        .status()
        .map_err(|e| format!("spawn talosctl: {}", e))?;
    if !status.success() {
        return Err(format!("talosctl exited {:?}", status.code()));
    }
    let cp = std::fs::read_to_string(out.join("controlplane.yaml"))
        .map_err(|e| e.to_string())?;
    let worker =
        std::fs::read_to_string(out.join("worker.yaml")).map_err(|e| e.to_string())?;
    let secrets = std::fs::read_to_string(out.join("secrets.yaml"))
        .or_else(|_| std::fs::read_to_string(out.join("talosconfig")))
        .unwrap_or_default();
    let _ = PathBuf::from(out);
    Ok((cp, worker, secrets))
}

fn gen_template_stub(
    name: &str,
    endpoint: &str,
    talos_version: &str,
    kubernetes_version: &str,
) -> (String, String, String) {
    let ep = endpoint.trim_start_matches("https://").trim_start_matches("http://");
    let cp = format!(
        r#"# Generated by TCS (template stub — install talosctl for full secrets)
version: v1alpha1
machine:
  type: controlplane
  install:
    image: ghcr.io/siderolabs/installer:{talos_version}
cluster:
  clusterName: {name}
  controlPlane:
    endpoint: https://{ep}
  network:
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  # WARNING: secrets not generated. Run: talosctl gen config {name} https://{ep}
"#
    );
    let worker = format!(
        r#"# Generated by TCS (template stub)
version: v1alpha1
machine:
  type: worker
  install:
    image: ghcr.io/siderolabs/installer:{talos_version}
cluster:
  clusterName: {name}
  controlPlane:
    endpoint: https://{ep}
  network:
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
# kubernetesVersion hint: {kubernetes_version}
"#
    );
    let secrets = format!(
        "# secrets stub for cluster {name}\n# Install talosctl and re-run generate for real secrets.\n"
    );
    (cp, worker, secrets)
}
